stages:
  - build
  - test
  - docker
  - deploy
  - cleanup

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest
  REGISTRY_TAG: $CI_COMMIT_SHORT_SHA

test_backend:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet restore backend/backend.csproj
    - dotnet test backend/backend.csproj --no-restore
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "continous-deployment"'

build_backend:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet restore backend/backend.csproj
    - dotnet build backend/backend.csproj --no-restore
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "continous-deployment"'

build_frontend:
  stage: build
  image: node:22
  script:
    - cd frontend
    - npm ci
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "continous-deployment"'

docker_build_utils:
  stage: docker
  image: docker:latest
  tags:
    - docker
  script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker buildx build -f deploy/Dockerfile-utilities -t $CI_REGISTRY_IMAGE/utilities:latest --push deploy/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "continous-deployment"'

docker_build_push:
  stage: docker
  image: docker:latest
  tags:
    - docker
  script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker buildx build -f deploy/Dockerfile --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$REGISTRY_TAG --cache-from=$CI_REGISTRY_IMAGE:$REGISTRY_TAG --push .
    - docker buildx build -f deploy/Dockerfile --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:test-$REGISTRY_TAG --cache-from=$CI_REGISTRY_IMAGE:test-$REGISTRY_TAG --push .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "continous-deployment"'
  needs:
    - docker_build_utils
    - build_backend
    - build_frontend

deploy_api:
  stage: deploy
  image: ${CI_REGISTRY_IMAGE}/utilities:latest
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAMESPACE_SLUG-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.doe25.swarm.chas-lab.dev/docs
    on_stop: stop_review
  script:
    - cd deploy
    - python3 deploy.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "continous-deployment"'
  needs:
    - job: docker_build_push
    - job: docker_build_utils

stop_review:
  stage: cleanup
  image: $CI_REGISTRY_IMAGE/utilities:latest
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - cd deploy
    - python3 delete-stack.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "continous-deployment"'
      when: manual

notify_discord:
  stage: cleanup
  image: curlimages/curl:latest

  script:
    - |
      curl -H "Content-Type: application/json" \
      -X POST \
      -d "{\"content\":\" Pipeline finished for branch: $CI_COMMIT_BRANCH\"}" \
      $DISCORD_WEBHOOK

  when: always

  rules:
    - if: '$CI_COMMIT_BRANCH'
