using System.ComponentModel.DataAnnotations;
using backend.Domain.Enums;

namespace backend.Domain.Entities
{
    public class AthleteProfile
    {
        // PK - Mirrors User.UserId
        public string UserId { get; set; } = null!;

        // Public URL id generated by SQL Server.
        public int PublicProfileId { get; set; }

        // Identity
        public required User User { get; set; }

        // Athlete Information
        public DateTime DateOfBirth {  get; set; }
        public bool IsMinor => DateOfBirth > DateTime.UtcNow.AddYears(-18);
        public Gender Gender { get; set; }

        // Athletic Information
        [StringLength(100)]
        public string? Sport { get; set; }

        [StringLength(500)]
        public string? Bio { get; set; }
        
        [StringLength(500)]
        public string? DreamGoal { get; set; }

        [StringLength(500)]
        public string? PhotoUrl { get; set; }
        
        [StringLength(500)]
        public string? PhotoPublicId { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Guardian (for minors only)
        public string? GuardianId { get; set; }
        public Guardian? Guardian { get; set; }

        // Navigation
        public ICollection<Post> Post { get; set; } = [];
        public ICollection<AthleteSport> Sports { get; set; } = [];
    }
}
