using System.ComponentModel.DataAnnotations;
using backend.Domain.Enums;

namespace backend.Domain.Entities;

public class SponsorProfile
{
    // PK  - Mirrors User.UserId
    public string UserId { get; set; } = null!;

    // Public URL id generated by SQL Server.
    public int PublicProfileId { get; set; }

    // Identity
    public required User User { get; set; }

    // Company Information
    public SponsorCategory SponsorTypeId { get; set; }

    [StringLength(200)]
    public required string Name { get; set; }

    [StringLength(500)]
    public string? Description { get; set; }

    [StringLength(20)]
    public required string OrganisationNumber { get; set; }

    [StringLength(500)]
    public string? PhotoUrl { get; set; }
    
    [StringLength(500)]
    public string? PhotoPublicId { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public ICollection<Donation> Donations { get; set; } = [];
}
